name: eegexpy-streaming
channels:
    - conda-forge
    - defaults
dependencies:
    # System-level dependencies
    - python>=3.8
    - liblsl # install liblsl to prevent error on macOS and Ubuntu: "RuntimeError: LSL binary library file was not found."
    - pip
    - pip:
      # Install package with Analysis + Streaming requirements
      - -e ..[streaming]