name: eegexpy-docsbuild
channels:
    - conda-forge
    - defaults
dependencies:
    # System-level dependencies
    - python>=3.8
    - pytables # install pytables for macOS arm64, so do not need to build from source.
    - pip
    - pip:
      # Install package with only Analysis requirements
      - -e ..[docsbuild]