name: Docs

on:
  push:
    branches: [ master, develop, 'dev/*' ]
  pull_request:
    branches: [ master, develop ]
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0   
        
    - name: Set up Python
      if: github.event.action != 'closed'
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        
    - name: Install dependencies
      if: github.event.action != 'closed'
      run: |
        make install-deps-apt
        python -m pip install --upgrade pip wheel
        python -m pip install attrdict

        make install-deps-wxpython
        
    - name: Build project
      if: github.event.action != 'closed'
      run: |
        make install-docs-build-dependencies


    - name: Get list of changed files
      if: github.event.action != 'closed'
      id: changes
      run: |
        git fetch origin master
        git diff --name-only origin/master...HEAD > changed_files.txt
        cat changed_files.txt


    - name: Determine build mode
      if: github.event.action != 'closed'
      id: mode
      run: |
        if grep -vqE '^examples/.*\.py$' changed_files.txt; then
          echo "FULL_BUILD=true" >> $GITHUB_ENV
          echo "Detected non-example file change. Full build triggered."
        else
          CHANGED_EXAMPLES=$(grep '^examples/.*\.py$' changed_files.txt | paste -sd '|' -)
          echo "FULL_BUILD=false" >> $GITHUB_ENV
          echo "CHANGED_EXAMPLES=$CHANGED_EXAMPLES" >> $GITHUB_ENV
          echo "Changed examples: $CHANGED_EXAMPLES"
        fi


    - name: Cache built documentation
      if: github.event.action != 'closed'
      id: cache-docs
      uses: actions/cache@v4
      with:
        path: |
          doc/_build/html
        key: ${{ runner.os }}-sphinx-${{ hashFiles('examples/**/*.py', 'doc/**/*', 'conf.py') }}
        restore-keys: |
          ${{ runner.os }}-sphinx-


    - name: Build docs
      if: github.event.action != 'closed'
      run: |
        make docs


    - name: Upload docs artifact
      if: github.event.action != 'closed'
      uses: actions/upload-artifact@v4
      with:
        name: docs-${{ github.sha }}
        path: doc/_build/html


    - name: Deploy PR Preview
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      uses: rossjrw/pr-preview-action@v1
      with:
        source-dir: doc/_build/html
        preview-branch: gh-pages
        umbrella-dir: pr-preview
        action: deploy

    - name: Remove PR Preview
      if: github.event_name == 'pull_request' && github.event.action == 'closed'
      uses: rossjrw/pr-preview-action@v1
      with:
        source-dir: doc/_build/html
        preview-branch: gh-pages
        umbrella-dir: pr-preview
        action: remove

        
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'  # TODO: Deploy seperate develop-version of docs?
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/_build/html
